config/routes.rb
Blog::Application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :body, presence: true

  before_validation :set_current_user, on: :create

  private
    
    def set_current_user
      self.user_id = User.current.id
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  before_validation :set_current_user, on: :create

  private
    
    def set_current_user
      self.user_id = User.current.id
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  def admin?
    false
  end

  def username
    email.gsub(/@(.*)$/, "")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  protect_from_forgery with: :exception
  before_filter :set_current_user


  def set_current_user
    User.current = current_user
  end

  def pundit_user
    current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authorize_comment, only: [:edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
    authorize_comment
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@post, @comment], notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@post, @comment] }
        format.js   { }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js   { }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to [@post, @comment], notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end

    def authorize_comment
      authorize @comment
      rescue => e
      redirect_to (request.env["HTTP_REFERER"] || root_path), notice: "Not allow to #{params[:action]} this comment"
      return 
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
    authorize_post
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authorize_post
      authorize @post
      rescue => e
      redirect_to (request.env["HTTP_REFERER"] || root_path), notice: "You are not allowed to #{params[:action]} this post"
      return 
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @posts = Post.limit(10).order(created_at: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_edit(url, options={}, &block)
    content = content_tag(:span, "", class: "glyphicon glyphicon-edit")
    content += capture(&block) if block_given?
    link_to content, url, options 
  end

  def link_to_destroy(url, options={}, &block)
    last_obj = url
    last_obj = url.last if url.is_a? Array
    options = { method: :delete, data: { confirm: "Are you sure you want to annihilate this #{last_obj.class.name.humanize.downcase}? Once annihilated, by definition it cannot be reconstituted." } }.merge(options)
    content = content_tag(:span, "", class: "glyphicon glyphicon-fire")
    content += capture(&block) if block_given?
    link_to content, url, options
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.valid? -%>
  $('#comments').append($("<%= escape_javascript(render('posts/comment', comment: @comment)) -%>").hide().fadeIn(1000));
  $('#comment_errors').html("");
  $('#comment_body').val("");
<% else -%>
  $('#comment_errors').html("<%= escape_javascript(render('posts/comment_errors', comment: @comment)) -%>");
<% end -%>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', [@post, comment] %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(@post, comment) %></td>
        <td><%= link_to 'Destroy', [@post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_post_comment_path(@post) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path(@post) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-right
        = render 'layouts/user_information'

app/views/layouts/_navigation_links.html.haml
-# add navigation links to this file
/%li{class: (request.url =~ /\/posts/ ? "active" : "")}= link_to "Posts", posts_path

app/views/layouts/_user_information.html.haml
- if current_user.present?
  %li.dropdown
    = link_to "#", class: "dropbdown-toggle", data: {toggle: "dropdown"} do
      %span.glyphicon.glyphicon-user
      = current_user.username
      %span.caret
    %ul.dropdown-menu{role: "menu"}
      %li= link_to "Update Profile", edit_user_registration_path
      %li= link_to "Sign Out", destroy_user_session_path, method: :delete
- else
  = link_to "Log in", new_user_session_path
  \|
  = link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <main role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>

</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/posts/_comment.html.erb
<li class="list-group-item">
  <h4 class="list-group-item-heading">
    <%= comment.user.try(:username) -%> 
    <small>posted <%= time_ago_in_words(comment.created_at) -%> ago</small>
  </h4>
  <p class="list-group-item-text">
    <%= simple_format(comment.body) %>
    <div class="clearfix">
      <div class="pull-right">
        <% if policy(comment).edit? %>
          <%= link_to_edit(edit_post_comment_path(comment.post, comment)){ " Edit" } %>
        <% end -%>
        <% if policy(comment).destroy? %>
          <%= link_to_destroy([comment.post, comment]){ " Annihilate" } %>
        <% end %>
      </div>
    </div>
  </p>
</li>

app/views/posts/_comment_errors.html.erb
<% if comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
    <% comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post) do |f| %>
  <%= f.error_summary %>

  <%= f.text_field :title %>
  <%= f.text_area :body, style: "height: 500px;" %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="page-header text-center">
  <h1>Naegles Bagels Blog</h1>
</div>

<ul class="list-group">
  <% @posts.each do |post| %>
    <li class="list-group-item">
      <h3 class="list-group-item-heading">
        <%= post.title %>
        <small>
          Posted by <%= post.user.try(:username) -%> 
          <%= time_ago_in_words(post.created_at) -%> ago
        </small>
      </h4>
      <p class="list-group-item-text">
        <div class="well">
          <%= simple_format(post.body) %>
        </div>
        <div class="pull-right">
          <% if policy(post).edit? %>
            <%= link_to_edit(edit_post_path(post)){ " Edit" } %>
          <% end %>
          <% if policy(post).destroy? %>
            <%= link_to_destroy(post){ " Annihilate" } %>
          <% end %>
        </div>
      </p>
      <% if last_comment = post.comments.last %>
        <blockquote>
          <p>
            <%= last_comment.body %>
          <p>
          <footer>
            Posted by <%= last_comment.user.try(:username) %> <%= time_ago_in_words last_comment.created_at %> ago
          </footer>
        </blockquote>
      <% end %>
      <%= link_to pluralize(post.comments.count, "comment"), post %>
    </li>
  <% end %>
</ul>
<br>

<%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>
  <%= @post.title -%>
  <% if policy(@post).edit? %>
    <%= link_to_edit edit_post_path(@post) %>
  <% end -%>
  <% if policy(@post).destroy? %>
    <%= link_to_destroy @post %>
  <% end -%>
  <small>Posted by <%= @post.user.try(:username) -%> <%= time_ago_in_words(@post.created_at) %> ago</small>
</h1>

<div class="well">
  <%= simple_format(@post.body) %>
</div>

<h2>Comments</h2>

<ul id="comments" class="list-group">
  <% @post.comments.order(:created_at).each do |comment| %>
    <%= render 'comment', :comment => comment %>
  <% end %>
</ul>

<% if policy(Comment.new).new? %>
<%= bootstrap_form_for [@post, @post.comments.build], remote: true do |f| %>
  <div id="comment_errors">
    <%= render 'comment_errors', comment: @comment -%>
  </div>

  <p>
    <b>New Comment</b>
    <br/>
    <%= f.text_area :body, hide_label: true %>
  </p>
  <div class="actions">
    <%= f.submit "Add Comment" %>
  </div>
<% end -%>
<% else -%>
  <p class="text-center text-warning">
    You must <%= link_to "log in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %> to comment on a post.
  </p>
<% end %>

<%= link_to 'Back', posts_path %>